baseURL: ""
languageCode: en-us
title: My Hugo Site
theme: PaperMod

params:
  homeInfoParams:
    Title: "Greetings"
    Content: Welcome to my site. Checkout my Socials!
  socialIcons:
    - name: Twitter
      url: "https://twitter.com/VirmaniAkshat"
  cover: 
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true


menu:
  main:
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 18
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 20
  - identifier: archives
    name: Archives
    url: /archives/
    weight: 20